If you would like to use the provided save file instead of Random World, take Bimais1068_01_01.ck2 from the mod file in Crusader Kings II->mod->cyber_kings_nyc and place it into Crusader Kings II->cyber_kings_nyc->save games

Join the following Discord Servers to discuss the mod:
Mafia Kings https://discord.gg/M4epPQW (NYC map)

Cyber Kings https://discord.gg/QDKFFdR (sci fi stuff)

Map topology and gfx assets provided by the Mafia Kings team

Provinces and history files generated by Zombaxx using ck2maptools using the topology and province maps from Mafia Kings as inputs
https://forum.paradoxplaza.com/forum/threads/tools-ck2maptools-automating-some-of-the-map-generation-process.1116396/

Lite Sci Fi features such as cybernetics and cloning available through the offmap empire are from the Middle Mars mod, with assets from the ck2 Sci-Fi full conversion mod COTC with permission from Galle the creator (who all us gave us permission to use some of his earlier work too)
https://discord.gg/DZ68Afv 

Other added features and events such as mechs were created by Rwmroy, who also added other features with permission from the following (unless they have been inactive for years, in that case and if you don't approve my apologies and please let us know.)
Sinstar- Hostage Mod, Siege Events, Visit Chamber, etc
mTA- Punishments & Executions
Sarc's blacksmith mod
Dragatus- Release vassal as tributary
Faiterial's buildings
Cipher's More Realm Laws (Army Professionalism and tax laws)
Nuubialainen- Personal Castle Mod (training yard, library events )
DaMonkey- Knights and Squires

Feudal New York Backstory:

The United States remained suspended for 100s of years in a 1920s-like state by Mafia and corporate politicians delaying the Big Crash by hindering any progress that was not 
directly related to perpetual short-term profits at the expensive of the populace, or enhancements for the powerful such as breakthroughs in cybernetic technologies. 

When the delayed Great Crash finally came it was as if the momentum had exponentially grown since the long era had begun in the 1920s. It was not only Wall Street that crashed, 
it was a ticket back to the Dark Ages for Earth-bound society at large as governments shattered synchronously with the breakdown of most supply lines and infrastructure needed 
to produce electronics, mechanics, and most modern goods. New York City was considered a safe zone protected by the corporations, and unofficially by the syndicates, as the 
outside world decayed into wasteland. Those not affiliated with these organizations, and without power of their own, became the new serfs of this post-corporate neofeudal era 
of fractured urban dystopias.

Even though the world has devolved back into a mostly low-tech mafia and corporate-remnant controlled feudalism in a literal sense in the centuries that followed, the surviving skyscrapers of The City have become more important than ever with most of the world outside the city walls being an uninhabitable wasteland, severely limiting horizontal living area. Because most technical efforts are put toward maintaining the skyscrapers and the walls, guns have become extremely uncommon as a result and were largely confiscated and destroyed by the federal government of old shortly before its collapse, and melee weapons once against rule battles.
