If you would like to use the provided save file instead of Random World, take Bimais1068_01_01.ck2 from the mod file in Crusader Kings II->mod->cyber_kings_nyc and place it into Crusader Kings II->cyber_kings_nyc->save games

Join the following Discord Servers to discuss the mod:
Mafia Kings https://discord.gg/M4epPQW (NYC map)

Cyber Kings https://discord.gg/QDKFFdR (sci fi stuff)

Map topology and gfx assets provided by the Mafia Kings team

Provinces and history files generated by Zombaxx using ck2maptools using the topology and province maps from Mafia Kings as inputs
https://forum.paradoxplaza.com/forum/threads/tools-ck2maptools-automating-some-of-the-map-generation-process.1116396/

Lite Sci Fi features such as cybernetics and cloning available through the offmap empire are from the Middle Mars mod, with assets from the ck2 Sci-Fi full conversion mod COTC with permission from Galle the creator (who all us gave us permission to use some of his earlier work too)
https://discord.gg/DZ68Afv 

Other added features and events such as mechs were created by Rwmroy, who also added other features with permission from the following (unless they have been inactive for years, in that case and if you don't approve my apologies and please let us know.)
Sinstar- Hostage Mod, Siege Events, Visit Chamber, etc
mTA- Punishments & Executions
Sarc's blacksmith mod
Dragatus- Release vassal as tributary
Faiterial's buildings
Cipher's More Realm Laws (Army Professionalism and tax laws)
Nuubialainen- Personal Castle Mod (training yard, library events )
DaMonkey- Knights and Squires